### ISSUE TITLE
Error compiling in SlideshowFX-util DialogHelper

### ISSUE THREAD

**Issue by ap13p** [twasyl/SlideshowFX#1]
Hi, I just got an error when I build it with ./gradlew.bat assemble just like you said in twitter last time. I have use my windows.
The error are failed to import this:
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;

I have use java version 1.8.0_31
$javac -version
1.8.0_31
$java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) Client VM (build 25.40-b25, mixed mode)

**Comment by twasyl** [comment]
Hi,

Due to recent changes, a _JDK 8 update 40_ is mandatory for building the application. When you have this set up, you can do the following to build the application:

```
gradlew.bat installSlideshowFX
```

Or if you have grade installed on your system you can do the following:

```
gradle installSlideshowFX
```

Moreover you will need to have _JAVA_HOME_ set properly for your system.

**Comment by ap13p** [comment]
Ok, thanks for the answer. I can build it now :+1:
