### ISSUE TITLE
LeapLib.so related failure on linux_x64

### ISSUE THREAD

**Issue by Hillrunner2008** [twasyl/SlideshowFX#16]
I have tried replacing the LeapLib.so library with a version pulled from the lated .deb package with the same result. This issue may overlap with the goal of stripping the requirement for the LeapMotion control dependencies. It would be great to be able to run this on Linux if a workaround could be suggested.

Output
`INFO: Starting Felix
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)`

**Comment by twasyl** [comment]
When I was on Linux, I had the same problem. Even on OS X and Windows a similar error occurs and make the application crash. Even when running the application as `root` or with admin privileges this error occurs sometimes.

I have the plan to externalize the LeapMotion feature (see #3) in order to deactivate it if the user has no plan to use and 'avoid' such errors.

**Comment by twasyl** [comment]
Close this issue because of #20
