### ISSUE TITLE
Stuck on how to launch application

### ISSUE THREAD

**Issue by JerJohn15** [twasyl/SlideshowFX#17]
Hello, 

How do you launch this application via the command line? I've gone ahead and ran the `gradle build` command from the instructions in order to build the application, but from there I'm stuck on how to launch the application. I'm using a Linux virtual machine.

**Comment by twasyl** [comment]
Hello,

The easiest way to launch the application on Linux is to build an installer with the latest developments (branch `development`) by launching the following command:

`gradlew build -x test`

You will then find the installer in the `build`directory. Does this help?

**Comment by JerJohn15** [comment]
Hello @twasyl, 

Yes, I've done that already but when I try to install the application in my desired folder location, using the "SlideshowFXSetup.sh" file, I get a "Error copying application artifact" message:

![application error when installing](https://cloud.githubusercontent.com/assets/6578161/19647198/00f4ccb4-99cb-11e6-9390-b93901007c38.png)

**Comment by twasyl** [comment]
Hello @JerJohn15,

Are you sure you're building the installer on the git `development` branch and not the `master` one? Because we have a typo error in the setup script that is currently corrected in the #14  PR.

If the installer is built from the `development` branch, could you then try to change the installation location from `/root` to a folder in your home directory for example? (to check if it may be a permission issue).

Thanks

**Comment by twasyl** [comment]
Closing this issue as no update.
