### ISSUE TITLE
'Define'-button not working

### ISSUE THREAD

**Issue by fvanwesterop** [twasyl/SlideshowFX#7]
I'm test-driving SlideshowFX: Cloned version 1.0, builded it with gradlew, ran the resulting installer on my Macbook (OSX 10.11.6) and started the app.

Now, either when I'm opening an existing presentation (from the included examples folder) or start a new one (using a template from the examples folder), whatever content I try to add or edit in the editor on the right, it will not show in the sheet on the left: CMD-Enter does nothing and also the 'Define' button does nothing and seems disabled (greyed-out).

Is this a user error? If so, how? Or indeed a bug?

**Comment by twasyl** [comment]
Hi,

In order to be able to define the content of an element on a slide, you will need what is called a `markup` plugin. A markup plugin allows you to define the content for slides in a particular markup language.

During the installation process, did you select one of the provided plugins (selection is made by clicking on a plugin, and it should become green) ? Currently SlideshowFX is shipped with:
- the HTML markup plugin ;
- the asciidoctor markup plugin ;
- the markdown markup plugin ;
- the textile markup plugin.

If you haven't select one of these plugins and have builded the application from the source, you can find the HTML markup plugin in `<repository_clone_location>/SlideshowFX-html/build/libs/SlideshowFX-html-1.0.jar` or dowload it [here](https://bintray.com/twasyl/SlideshowFX/SlideshowFX-html#files/com/twasyl/slideshowfx/SlideshowFX-html/1.0) . In order to install the plugin, in SlideshowFX, go to the `Options` > `Install plugin` menu entry and select the previous JAR.

Now, when you double click on an element of a slide, you should be able to select the HTML syntax on the top of the text area containing the content to define. Once `HTML` (or other one) is selected, you will be able to define the content (the `Define` button shouldn't be greyed-out anymore).

Does it solve your problem?

Cheers.

**Comment by fvanwesterop** [comment]
Hi Thierry,

Thanks for your quick response! And yes indeed, missing markup plugins
seemed to be the problem!

I was pretty sure I did select a number of component when I ran the
installer, namely the 'Content extensions', 'Snippet Executors' and
'Hosting connectors'. I selected some in each of these. However I
overlooked the section 'Markups' at the top entirely. I just started with
selecting 'Content extensions' in the installation wizard and went down
from there.

Re-installed the lot and now it seems to be working fine!

Cheers!
Frank

**Comment by twasyl** [comment]
Hi,

Glad it is working for you with this solution. Maybe I should select at least the HTML markup plugin by default and make the selection of at least one markup plugin mandatory in the installer.

Cheers,
Thierry

**Comment by fvanwesterop** [comment]
Yes that's great, but still there 's something weird going on with the installer in that area: I first manually installed the HTML plugin by pointing the app to the jar, then indeed only the HTML plugin was available. Then I removed the app and re-installed, this time making sure I selected HTML, AsciiDoc and Markdown (but not Textile) in the installer wizard. But then also only the HTML plugin would be available in the app, not the other selected ones. Removed the app again and hunted for left-overs which I found in '~/Library/Application Support/SlideShowFX'. Reinstalled again, but this time ALL plugins are available even though I did not select the Textile plugin. Did the installation yet another time, now deliberately not selecting any of the markup plugins (presumably the error I made the first time), but still ALL plugins will be installed again... Does the installer perhaps cache settings somewhere?

**Comment by twasyl** [comment]
All plugins installed for the application are located in the
`~/.SlideshowFX/plugins` folder. You can remove this folder in order to
'clean' the installed plugins or remove specific plugins.

The installation wizard will not remove any of existing plugins ; only add
the plugins that are selected in the plugin selection step.

To be more general, to uninstall properly the application and start from
scratch, simply delete the `~/. SlideshowFX` folder.

Cheers
